SELECT B.YEAR YEAR, B.MAX_SIZE - A.SIZE_OF_COLONY YEAR_DEV, A.ID ID
FROM ECOLI_DATA A
LEFT JOIN 
    (SELECT YEAR(DIFFERENTIATION_DATE) YEAR, MAX(SIZE_OF_COLONY) MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)) B
        ON (B.YEAR = YEAR(A.DIFFERENTIATION_DATE))
ORDER BY YEAR, YEAR_DEV ASC